### ISSUE TITLE
Implement draft support of Configuration Roles

### ISSUE THREAD

**Issue by AlenPelin** [Sitecore/Sitecore.Diagnostics.ConfigBuilder#1]
There is an initiative to add support of roles to Sitecore configuration which is described here: https://gist.github.com/AlenPelin/ca183fda6d8a960e260c

While it is being agreed in Product Department, we need to implement draft support of this feature in Config Builder. Current draft looks following:

* `role:define` can be used to specify one or several roles, there are no pre-defined role in configuration engine level
* `role:define` can be placed anywhere any number of times and act as add this role to the list of defined ones, so the list can be extended, but not shortened
* `role:require` uses ` OR ` logic for pipe-separated-list items

```xml
<configuration xmlns:role="http://www.sitecore.net/xmlconfig/role">
  ...
  <sitecore role:define="authoring|publishing|delivery">
    ...
    <databases>
      ...
      <database id="master" ... role:require="authoring|publishing">
        ...
      </database>
      ...
    </databases>
    ...
    <scheduling>
      ...
      <agent type="Sitecore.Tasks.DatabaseAgent" method="Run" interval="00:10:00" role:require="authoring|publishing">
        <param desc="database">master</param>
        ...
      </agent>
      ...
      <agent type="Sitecore.Tasks.PublishAgent" method="Run" interval="00:00:00" role:require="publishing">
        ...
      </agent>
      ...
    </scheduling>
    ...
  </sitecore>
  ...
</configuration>
```

Points to consider:
1. Official documentation of xDB uses "Feature" term, however in my opinion "role" is shorter, easier to understand and harder to make a typo
2. With `role:require` supporting only pipe-separated list with ` OR ` logic it may be difficult to configure some complex cases, it would not be possible to enable part of the config only if two roles are defined. The solution would be add the support of simple conditions: ` & `, ` | `, ` ! `, ` ( expr ) `

**Comment by andrew-at-sitecore** [comment]
First of all - very useful initiative! The following are my considerations as I try to take "conservative" side.

My first concern is that there is no clear problem statement. My best understanding is:
 * We want to make sure that after installation of the product there is only necessary components being enabled ( for example there is no Aggregation agent running on CD servers )
 * We want to make further configuration management ( adding "patch" configuration straightforward ). For example that it is easy for the customer to apply patch provided by PSS team to the environment

My second concern is that the aforementioned initiative complicates Sitecore configuration engine ( which is already fairly complex thing ) and requires adding more code to the system.

---

If I try to think of an "organic" approach - I imagine the following:
 * Sitecore comes with minimal necessary confiugration ( "barebones" CMS )
 * Roles are installed as separate packages ( where each package contains configs [ideally - a separate folder] to activate certain role + piece of configuration which sets a setting like "Roles.<role-name-here>.Active=TRUE" so that it is easier to track what has been installed )
    * We may consider having such folder names starting with '#' symbol ensuring that they are applied first
 * Patches and stuff are "business as usual" - they are deployed to 'Include' folder and overwrite settings from "role" folders as necessary

PROBLEMS:
 * In which order patches are to be applied ( as you mentioned earlier )
 * Customers need to know to which server which "patch" needs to be deployed

**Comment by AlenPelin** [comment]
We tried another approach with adding to all config files their roles as Sitecore.Support.123456.CM.PUB.config which resolves the issue with ordering, but   sometimes the configs were deployed to wrong servers. That's why I see this solution is the most robust and reliable as it does not make any room for mistakes.
